export default [
    /* early war cards */
    { number: 1, name: "Asia Scoring", side: "neutral", location: "inactive", phase: "early", ops: 0, flags: ["scoring"] },
    { number: 2, name: "Europe Scoring", side: "neutral", location: "inactive", phase: "early", ops: 0, flags: ["scoring"] },
    { number: 3, name: "Middle East Scoring", side: "neutral", location: "inactive", phase: "early", ops: 0, flags: ["scoring"] },
    { number: 4, name: "Duck and Cover", side: "usa", location: "inactive", phase: "early", ops: 3 },
    { number: 5, name: "Five Year Plan", side: "usa", location: "inactive", phase: "early", ops: 3 },
    { number: 6, name: "The China Card", side: "neutral", location: "inactive", phase: "early", ops: 4 },
    { number: 7, name: "Socialist Governments", side: "ussr", location: "inactive", phase: "early", ops: 3 },
    { number: 8, name: "Fidel", side: "ussr", location: "inactive", phase: "early", ops: 2, flags: ["remove"] },
    { number: 9, name: "Vietnam Revolts", side: "ussr", location: "inactive", phase: "early", ops: 2, flags: ["remove"] },
    { number: 10, name: "Blockade", side: "ussr", location: "inactive", phase: "early", ops: 1, flags: ["remove"] },
    { number: 11, name: "Korean War", side: "ussr", location: "inactive", phase: "early", ops: 2, flags: ["remove"] },
    { number: 12, name: "Romanian Abdication", side: "ussr", location: "inactive", phase: "early", ops: 1, flags: ["remove"] },
    { number: 13, name: "Arab-Israeli War",     qside: "neutral", location: "inactive", phase: "early", ops: 2 },
    { number: 14, name: "Comecon", side: "ussr", location: "inactive", phase: "early", ops: 3, flags: ["remove"] },
    { number: 15, name: "Nasser", side: "ussr", location: "inactive", phase: "early", ops: 1, flags: ["remove"] },
    { number: 16, name: "Warsaw Pact Formed", side: "ussr", location: "inactive", phase: "early", ops: 3, flags: ["remove"] },
    { number: 17, name: "De Gaulle Leads France", side: "ussr", location: "inactive", phase: "early", ops: 3, flags: ["remove"] },
    { number: 18, name: "Captured Nazi Scientist", side: "neutral", location: "inactive", phase: "early", ops: 1, flags: ["remove"] },
    { number: 19, name: "Truman Doctrine", side: "usa", location: "inactive", phase: "early", ops: 1, flags: ["remove"] },
    { number: 20, name: "Olympic Games", side: "neutral", location: "inactive", phase: "early", ops: 2 },
    { number: 21, name: "NATO", side: "usa", location: "inactive", phase: "early", ops: 4, flags: ["remove"] },
    { number: 22, name: "Independent Reds", side: "usa", location: "inactive", phase: "early", ops: 2, flags: ["remove"] },
    { number: 23, name: "Marshall Plan", side: "usa", location: "inactive", phase: "early", ops: 4, flags: ["remove"] },
    { number: 24, name: "Indo-Pakistani War", side: "neutral", location: "inactive", phase: "early", ops: 2 },
    { number: 25, name: "Containment", side: "usa", location: "inactive", phase: "early", ops: 3, flags: ["remove"] },
    { number: 26, name: "CIA Created", side: "usa", location: "inactive", phase: "early", ops: 3, text: "USSR reveals hand this turn. Then the US may conduct operations as if they played a 1 Op card.", flags: ["remove"] },
    { number: 27, name: "US/Japan Defense Pact", side: "usa", location: "inactive", phase: "early", ops: 4, flags: ["remove"] },
    { number: 28, name: "Suez Crisis", side: "ussr", location: "inactive", phase: "early", ops: 3, flags: ["remove"] },
    { number: 29, name: "East European Unrest", side: "usa", location: "inactive", phase: "early", ops: 3 },
    { number: 30, name: "Decolonization", side: "ussr", location: "inactive", phase: "early", ops: 2 },
    { number: 31, name: "Red Scare/Purge", side : "neutral", location: "inactive", phase: "early", ops: 3, text: "All further Operations cards played by your opponent this turn are -1 to their value (to a minimum of 1 Op)." },
    { number: 32, name: "UN Intervention", side : "neutral", location: "inactive", phase: "early", ops: 1 },
    { number: 33, name: "De-Stalinization", side: "ussr", location: "inactive", phase: "early", ops: 3, text: "USSR may relocate up to 4 Influence points to non-US controlled countries. No more than 2 influence may be placed in the same country", flags: ["remove"] },
    { number: 34, name: "Nuclear Test Ban", side : "neutral", location: "inactive", phase: "early", ops: 4 },
    { number: 35, name: "Formosan Resolution", side: "usa", location: "inactive", phase: "early", ops: 2, flags: ["remove"] },
    { number: 103, name: "Defectors", side: "usa", location: "inactive", phase: "early", ops: 2 },

    /* mid war cards */
    { number: 36, name: "Brush War", side: "neutral", location: "inactive", phase: "mid", ops: 3 },
    { number: 37, name: "Central America Scoring", side: "neutral", location: "inactive", phase: "mid", ops: 0, flags: ["scoring"] },
    { number: 38, name: "Southeast Asia Scoring", side: "neutral", location: "inactive", phase: "mid", ops: 0, flags: ["scoring"] },

    /* late war cards */
    { number: 82, name: "Iranian Hostage Crisis", side: "ussr", location: "inactive", phase: "late", ops: 3, flags: ["remove"]  },
    { number: 83, name: "The Iron Lady", side: "usa", location: "inactive", phase: "late", ops: 3, flags: ["remove"]  },
    { number: 84, name: "Reagan Bombs Libya", side: "usa", location: "inactive", phase: "late", ops: 2, flags: ["remove"]  },

    /* optional cards */
    { number: 104, name: "The Cambridge Five", side: "ussr", location: "disabled", phase: "early", ops: 2, flags: ["optional", "remove"]  },
    { number: 105, name: "Special Relationship", side: "usa", location: "disabled", phase: "early", ops: 2, flags: ["optional", "remove"]  },
    { number: 106, name: "NORAD", side: "usa", location: "disabled", phase: "early", ops: 3, flags: ["optional", "remove"]  },
];