export default [
    { name: "Asia Scoring", side: "neutral", state: "inactive", phase: "early", ops: 0, flags: ["scoring"] },
    { name: "Europe Scoring", side: "neutral", state: "inactive", phase: "early", ops: 0, flags: ["scoring"] },
    { name: "Middle East Scoring", side: "neutral", state: "inactive", phase: "early", ops: 0, flags: ["scoring"] },
    { name: "Duck and Cover", side: "usa", state: "inactive", phase: "early", ops: 3 },
    { name: "Five Year Plan", side: "usa", state: "inactive", phase: "early", ops: 3 },
    { name: "The China Card", side: "neutral", state: "inactive", phase: "early", ops: 4 },
    { name: "Socialist Governments", side: "ussr", state: "inactive", phase: "early", ops: 3 },
    { name: "Fidel", side: "ussr", state: "inactive", phase: "early", ops: 2, flags: ["remove"] },
    { name: "Vietnam Revolts", side: "ussr", state: "inactive", phase: "early", ops: 2, flags: ["remove"] },
    { name: "Blockade", side: "ussr", state: "inactive", phase: "early", ops: 1, flags: ["remove"] },
    { name: "Korean War", side: "ussr", state: "inactive", phase: "early", ops: 2, flags: ["remove"] },
    { name: "Romanian Abdication", side: "ussr", state: "inactive", phase: "early", ops: 1, flags: ["remove"] },
    { name: "Arab-Israeli War", side: "neutral", state: "inactive", phase: "early", ops: 2 },
    { name: "Comecon", side: "ussr", state: "inactive", phase: "early", ops: 3, flags: ["remove"] },
    { name: "Nasser", side: "ussr", state: "inactive", phase: "early", ops: 1, flags: ["remove"] },
    { name: "Warsaw Pact Formed", side: "ussr", state: "inactive", phase: "early", ops: 3, flags: ["remove"] },
    { name: "De Gaulle Leads France", side: "ussr", state: "inactive", phase: "early", ops: 3, flags: ["remove"] },
    { name: "Captured Nazi Scientist", side: "neutral", state: "inactive", phase: "early", ops: 1, flags: ["remove"] },
    { name: "Truman Doctrine", side: "usa", state: "inactive", phase: "early", ops: 1, flags: ["remove"] },
    { name: "Olympic Games", side: "neutral", state: "inactive", phase: "early", ops: 2 },
    { name: "NATO", side: "usa", state: "inactive", phase: "early", ops: 4, flags: ["remove"] },
    { name: "Independent Reds", side: "usa", state: "inactive", phase: "early", ops: 2, flags: ["remove"] },
    { name: "Marshall Plan", side: "usa", state: "inactive", phase: "early", ops: 4, flags: ["remove"] },
    { name: "Indo-Pakistani War", side: "neutral", state: "inactive", phase: "early", ops: 2 },
    { name: "Containment", side: "usa", state: "inactive", phase: "early", ops: 3, flags: ["remove"] },
    { name: "CIA Created", side: "usa", state: "inactive", phase: "early", ops: 3, text: "USSR reveals hand this turn. Then the US may conduct operations as if they played a 1 Op card.", flags: ["remove"] },
    { name: "US/Japan Defense Pact", side: "usa", state: "inactive", phase: "early", ops: 4, flags: ["remove"] },
    { name: "Suez Crisis", side: "ussr", state: "inactive", phase: "early", ops: 3, flags: ["remove"] },
    { name: "East European Unrest", side: "usa", state: "inactive", phase: "early", ops: 3 },
    { name: "Decolonization", side: "ussr", state: "inactive", phase: "early", ops: 2 },
    { name: "Red Scare/Purge", side : "neutral", state: "inactive", phase: "early", ops: 3, text: "All further Operations cards played by your opponent this turn are -1 to their value (to a minimum of 1 Op)." },
    { name: "UN Intervention", side : "neutral", state: "inactive", phase: "early", ops: 1 },
    { name: "De-Stalinization", side: "ussr", state: "inactive", phase: "early", ops: 3, text: "USSR may relocate up to 4 Influence points to non-US controlled countries. No more than 2 influence may be placed in the same country", flags: ["remove"] },
    { name: "Nuclear Test Ban", side : "neutral", state: "inactive", phase: "early", ops: 4 },
    { name: "Formosan Resolution", side: "usa", state: "inactive", phase: "early", ops: 2, flags: ["remove"] },
    { name: "Defectors", side: "usa", state: "inactive", phase: "early", ops: 2 },

    { name: "Brush War", side: "neutral", state: "inactive", phase: "mid", ops: 3 },
    { name: "Central America Scoring", side: "neutral", state: "inactive", phase: "mid", ops: 0, flags: ["scoring"] },
    { name: "Southeast Asia Scoring", side: "neutral", state: "inactive", phase: "mid", ops: 0, flags: ["scoring"] },

    { name: "Iranian Hostage Crisis", side: "ussr", state: "inactive", phase: "late", ops: 3, flags: ["remove"]  },
    { name: "The Iron Lady", side: "usa", state: "inactive", phase: "late", ops: 3, flags: ["remove"]  },
    { name: "Reagan Bombs Libya", side: "usa", state: "inactive", phase: "late", ops: 2, flags: ["remove"]  },

    { name: "The Cambridge Five", side: "ussr", state: "disabled", phase: "early", ops: 2, flags: ["optional", "remove"]  },
    { name: "Special Relationship", side: "usa", state: "disabled", phase: "early", ops: 2, flags: ["optional", "remove"]  },
    { name: "NORAD", side: "usa", state: "disabled", phase: "early", ops: 3, flags: ["optional", "remove"]  },
];